/vis/open OGL
/vis/viewer/set/viewpointVector 0 -1 0.0001
/vis/drawVolume

/vis/geometry/set/forceSolid logicdetVol 1 true
/vis/geometry/set/forceSolid logicSheet 1 true


/vis/geometry/set/colour logicdetVol 1 0.66 0.9 0.7 0.5
/vis/geometry/set/colour logicSheet 1 0.0 1.0 0.5 1.0


/vis/viewer/set/autoRefresh true
/vis/scene/add/trajectories smooth
/vis/scene/add/scale 10  cm
/vis/scene/add/axes
/vis/scene/add/eventID
/vis/scene/endOfEventAction accumulate
