/vis/open OGLIX
/run/initialize

# View settings
/vis/viewer/set/viewpointVector 0.0 0.0 1.0 
/vis/drawVolume
#/vis/viewer/zoom 5
#/vis/scene/add/scale 10  cm
#/vis/scene/add/axes
/vis/viewer/set/autoRefresh true
/vis/scene/add/trajectories smooth
/vis/scene/add/eventID
/vis/scene/endOfEventAction accumulate

# Set colors
/vis/geometry/set/colour logicHPGe   1.0 0.55 0.0        # orange
/vis/geometry/set/colour logicNaI    0.0 0.0 1.0         # blue
/vis/geometry/set/colour logicNaIClad 0.75 0.75 0.75 0.5 # silver with 50% transparency
/vis/geometry/set/colour logicCryostat 0.59 0.29 0.0 0.5 # brown with 50% transparency

# Force solid drawing (required for fill colors to appear)
/vis/geometry/set/forceSolid logicHPGe 1 true
/vis/geometry/set/forceSolid logicNaI 1 true
/vis/geometry/set/forceSolid logicNaIClad 1 true
/vis/geometry/set/forceSolid logicCryostat 1 true

